import React, {PropTypes} from 'react'
import Header from '../../shared/components/header'
import Store from '../../shared/store'
import Layout from '../../shared/components/layout'
import Footer from '../../shared/components/footer'
import TopNav from '../../shared/components/topnav'
import LeftNav from '../../shared/components/leftnav'
import Content from '../../shared/components/content'
import Table from '../../shared/components/table'
