import React, { Component, PropTypes } from 'react'
import DropDown from '../dropDown'
import Layout from '../layout'
import {
  TextField
} from 'material-ui'
import { contextTypes } from '../../decorators'

/** TODO: Make this replace the layouts generated by the details component, so
 *        the that details component can be used as follows:
 *        <Details title="Example Title">
 *          <DetailsRow label="Text"><MaterialUI.TextField /></DetailsRow>
 *        </Details>
 */

@contextTypes({ muiTheme: PropTypes.object })
class DetailRow extends Component {
  render() {
    let style = this.props.style(this.props.type, this.context.muiTheme, this.props);
    return (
      <div style={style.row}>
        <Layout widths={this.props.layout}
                cPadding={this.props.cPadding}
                cStyles={style.cStyles}
                cStyle={style.cStyle}>

          <div style={style.label}>{this.props.label}</div>
          <div style={style.value}>{this.props.children}</div>

        </Layout>
      </div>
    );
  }
}

export default DetailRow;
