import React, { Component, PropTypes } from 'react'
import DropDown from '../dropDown'
import Layout from '../layout'
import {
  TextField
} from 'material-ui'
import { contextTypes } from '../../decorators'
import _ from 'lodash'

/** TODO: Make this replace the layouts generated by the details component, so
 *        the that details component can be used as follows:
 *        <Details title="Example Title">
 *          <DetailsRow label="Text"><MaterialUI.TextField /></DetailsRow>
 *        </Details>
 */

@contextTypes({ muiTheme: PropTypes.object })
class DetailRow extends Component {
  render() {
    let style = this.props.getStyle(this.props.type, this.context.muiTheme, this.props);
    return (
      <div style={_.assign(style.row, this.props.rowStyle)}>
        <Layout widths={this.props.layout}
                cPadding={this.props.cPadding}
                cStyles={_.assign(style.cStyles, this.props.cStyles)}
                cStyle={_.assign(style.cStyle, this.props.cStyle)}>

          <div style={_.assign(style.label, this.props.labelStyle)}>{this.props.label}</div>
          <div style={_.assign(style.value, this.props.valueStyle)}>{this.props.children}</div>

        </Layout>
      </div>
    );
  }
}

export default DetailRow;
