import React from 'react'
import DropDown from '../dropDown'
import Layout from '../layout'
import {
  TextField
} from 'material-ui'

/** TODO: Make this replace the layouts generated by the details component, so
 *        the that details component can be used as follows:
 *        <Details title="Example Title">
 *          <DetailsRow label="Text"><MaterialUI.TextField /></DetailsRow>
 *        </Details>
 */

export default class DetailRow extends React.Component {
  render() {
    let style =
      this.props.style ||
      {
        row: {},
        label: {},
        value: {},
        cStyle: {},
        cStyles: {},
      };
    return (
      <div style={style.row}>
        <Layout widths={this.props.layout}
                cPadding={this.props.cPadding}
                cStyles={style.cStyles}
                cStyle={style.cStyle}>

          <div style={style.label}>{this.props.label}</div>
          <div style={style.value}>{this.props.children}</div>

        </Layout>
      </div>
    );
  }
}
