import React from 'react'
import DropDown from '../dropDown'
import {
  TextField
} from 'material-ui'

/** TODO: Make this replace the layouts generated by the details component, so
 *        the that details component can be used as follows:
 *        <Details title="Example Title">
 *          <DetailsRow label="Text"><MaterialUI.TextField /></DetailsRow>
 *        </Details>
 */

export default class DetailRow extends React.Component {

  render() {
    return (
      <div style={this.props.style.row}>
        <Layout widths={this.props.layout}
                cPadding={this.props.cPadding}
                cStyles={this.props.style.cStyles}
                cStyle={this.props.style.cStyle}>

          <div style={this.props.style.label}>{this.props.label}</div>
          <div style={this.props.style.value}>{this.props.children}</div>
          
        </Layout>
      </div>
    );
  }
}
