import React from 'react'

/** TODO: Make this replace the layouts generated by the details component, so
 *        the that details component can be used as follows:
 *        <Details title="Example Title">
 *          <DetailsRow label="Text"><MaterialUI.TextField /></DetailsRow>
 *        </Details>
 */

export default class DetailRow extends React.Component {
  render() {
    return (
      <div />
    );
  }
}
